### ISSUE TITLE
Navigation in case studies

### ISSUE THREAD

**Issue by smborio** [maths/stack-web#22]
I am due to upload at least one new case study by the end of the week. The last time I did this, sorting out the navigation within case studies was a bit of a nightmare. I am hoping to document things this time round to add it to the documentation in this repo but wanted to pose the question as to whether the navigation is valuable enough to keep or it could be simplified (eg don't navigate from the last back to the first and vice-versa).

**Comment by samfearn** [comment]
Hey, I think I can make a couple of changes to make adding a new case study easier, and not require multiple files to be edited. I'm working on a local branch and will make a pull-request soon (hopefully).

As a follow-up question, does anyone know if the ordering of the case studies under the case studies item in the nav bar is important, aside from them being grouped by year? That is, would anyone object if the specific ordering within the sub year were to change?

**Comment by smborio** [comment]
Thanks for that Sam. I personally cannot make sense of the order. I assumed it was according to publication date but that's not clear. I have no objection, the grouping by year is useful though.

**Comment by malthefogsporring** [comment]
I agree! In the ILIAS branch there is a new suggested layout for Projects, with a simple "All projects" return button at the top. I'll propose that this should also replace "Previous/next" buttons in the case studies!

**Comment by samfearn** [comment]
The problem I see at the moment is that when a new contributor decides to add a case study, they have to know to edit a number of different files: the actual new case study md file; the previous oldest case study, to set the new “next” link; the case studies overview page to add a new card; the mkdocs.yml file to add the page to the nav bar.

I propose we leverage the templating engine to simplify this process. One case study md file is created, with some minimal YAML metadata at the top, and everything else is done automatically. Then a new contributor can look at a template case study, and easily see how to create the new case study md file, and not have to mess with any existing files.

I have this mostly working, just need to finish some changes to the overview page tomorrow, then I’ll make a pull-request.

**Comment by sangwinc** [comment]
Yes, it is sometimes harder to make things simpler!   And, I really want to make it simple for people to add case studies.

1. I've brought the "projects" branch up to date with the master.  Thanks for starting that @malthefogsporring.  I'll ask the project leaders to contribute.  I like that kind of list structure.  If case studies are added without a link from a "main case studies page" that really doesn't break anything, and we can add in those links easily enough in due course
2. @samfearn, if you're able to push something please do.  I don't work on this (potentially at cross purposes!) until you are done.

Much appreciated everyone.

**Comment by samfearn** [comment]
I've put a new pull request in now which should simplify the creation and maintenance of case studies.

**Comment by smborio** [comment]
Thanks @samfearn for acting on this so quickly! I'm afraid my dev experience is not sufficient to confidently merge this so I will let others review. I started working on documentation on editing the website, I'll add instructions on this when the main guide is done.

**Comment by sangwinc** [comment]
@samfearn this is a real improvement, thanks!  
I've added the library to the workflows so the site rebuilds on push to master.
https://github.com/maths/stack-web/commit/62f2bfd2b56a26b98b6c8ccf8304943b25447e9f
The new additions are on the main website. https://stack-assessment.org/
